### PR TITLE
Streak Indicator

### PR DESCRIPTION
**Pull request by Shadallark**
I have added a label that displays the current streak count and a
UIImageView to hold the Streak Icon but I am having difficulties
figuring out how to set the icon.

There are more adjustments that I intend to make once I figure out how to set the icon.  

@vIiRuS and @kyle-fox  can you take a look at what I have done to set the image and provide some advice on what I am doing incorrectly?

### CODE REVIEW

**Comment by Shadallark** [comment]
Okay, I figured it out.  I will fix up the code, make the other changes I wanted to make and then update this pull request for you to test out for me.

**Comment by Shadallark** [comment]
This deals with issue #96 .

**Comment by vIiRuS** [comment]
Great! I'll take a look at this this evening!

**Comment by vIiRuS** [comment]
Hey,

There seems to be problems with the constraints. 
The imageview is missing height and width constraints.
screen shot 2015-08-14 at 18 39 29

The second thing isn't necessarily a problem, but a "nice to have". right now the streak label has a static width. Could you change that to scale with the content size? (You do this my setting the priority on the Width constraint to p.e. 500 and then set the Content Hugging Priority and Content Compression Resistance Priority on the label to 1000 for horizontal. The width constraint should then turn to a dotted line and the label will scale to fit the text it contains.

**Comment by Shadallark** [comment]
As always @vIiRuS your suggestions and recommendations are greatly appreciated.  It took me much longer than it should have but I have implemented width and aspect ratio constraints on the streakImage (initial attempts messed up the icon) and setup the resizing of the streakLabel as you suggested.  **This *should* be ready to go now.**

**Comment by Shadallark** [comment]
Hey there @vIiRuS .  I see that this Pull Request has some conflicts inherent in it.  Would you like me to retract this request and submit a new one with the conflicts resolved?

**Comment by vIiRuS** [comment]
Sorry that I didn't respond to this for so long.

Yes, it would be great if you could resolve the merge conflict, so I can easily merge it!

**Comment by Shadallark** [comment]
Closing this pull request to get it out of the way of a new one without conflicts.  I will post the new one tomorrow or the next day.

**Pull request closed without merging**
