### PR TITLE
Fixes #100

### LINKED ISSUE #100: Replace NSDate+TimeAgo with DateTools
NSDate+TimeAgo was merged with DateTools (and is thus not developed anymore)
https://github.com/MatthewYork/DateTools#time-ago

Probably just needs the Podfile entry changed and then adapted until there are no more errors

### PR DESCRIPTION
**Pull request by kyle-fox**

### CODE REVIEW

**Comment by vIiRuS** [comment]
Great! Thanks a lot. Can you provide your HabitRPG User ID for the contribution tier?

@crookedneighbor

**Comment by kyle-fox** [comment]
User ID is kylefox - Thanks!!

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by crookedneighbor** [comment]
It's a long string of numbers and letters, not the same as your login name.

**Comment by kyle-fox** [comment]
Whoops sorry about that.

16fa5d4d-6729-4a7d-af3e-26a25850b5b8

Thanks for the tip @crookedneighbor

**Comment by crookedneighbor** [comment]
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

**Pull request merged**
