### PR TITLE
New URLs and Twitter username

### PR DESCRIPTION
**Pull request by Taarna**
I've changed Twitter username and URLs for Community Guidelines, News and FAQ.

### CODE REVIEW

**Comment by vIiRuS** [comment]
Great. Thanks! :+1:

**Comment by crookedneighbor** [comment]
@Taarna This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by Taarna** [comment]
@crookedneighbor It's 921a3926-f598-47d2-8311-fa44230676d8. Thank you :)

**Comment by crookedneighbor** [comment]
I've awarded you your first contributor tier!

You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Pull request merged**
