### PR TITLE
Improve markdown support. Fixes #176

### LINKED ISSUE #176: Support for markdown
See how ```**word**``` does not do anything on the iOS client (v.1.0.2 on iOS 8.4.1). 
Related to #85. 

markdown in habitica - bug

### PR DESCRIPTION
**Pull request by revolter**
Added support for italic, bold and italic and bold preceded and followed by punctuation marks _(and other characters)_.

### CODE REVIEW

**Comment by vIiRuS** [comment]
Awesome! My regex understanding is very limited, so I was already worried I'd have to spend a lot of time reading docs to fix this one, so this is great.

What's your Habitica User-ID, for the contributor rank?

**Comment by revolter** [comment]
Well, for me it's opposite, I __love__ regex. I could improve them more if you want. I really wanted to ask you why have you created them like that. I could simplify them a lot but I was afraid you won't accept the PR so I kept the changes to a minimum.

If you want me to help with it, I would need some description for every regex and some examples that should and should not match. You can use [regex101](https://regex101.com) to input the test strings and then send me a permalink to it.

My user id is `3712e6e7-6bc1-40f9-87e2-5e3bbdfdc7c1`. Is this contributor rank public?

**Comment by vIiRuS** [comment]
The regexes weren't written by me. the code is from a different iOS app (iOctocat), as noted in the file headers. For the most parts it worked (with exception to the error this fixed), so I never bothered to see if there was a simpler/better solution.
The stuff it detects is markdown. The syntax for that is described here: https://daringfireball.net/projects/markdown/syntax
I can also provide you with test strings, if the syntax documentation isn't clear.

The contributor rank is public. you can see all ranks [here](https://habitica.com/#/options/groups/hall/heroes). And you can find more information on contributor ranks in the [Wiki article](http://habitica.wikia.com/wiki/Contributor_Rewards)

**Comment by revolter** [comment]
Sorry, I didn't see the file headers. I know it's about markdown and what it does. To complete my previous comment, I was referring for example to the username matching part, I could make a regex that matches any `@` followed by a string. The question would be if there is any specific case in which you don't what to match it as an username (e.g. @channel-name: To the left should not be matched, but @thisusername should match).

**Comment by vIiRuS** [comment]
Ah, that part. We're not actually using that currently, as Habitica usernames can also contain whitespaces (making it impossible to correctly get a username without having a list of existing usernames). I kept it around, in case we change that in the future and usernames can't have whitespaces. As we don't have something like @channel-name, I don't think there are any exceptions for the usernames

**Comment by revolter** [comment]
Ok, I'll document myself and try to come with simpler and cleaner regexes. Would it be ok if I'd open another PR?

**Pull request merged**
