### PR TITLE
Fix issue 1201

### PR DESCRIPTION
**Pull request by EricMiddelhove**
my Habitica User-ID: b79ce54a-b8d4-425c-be98-9a35da6a39b5

This Pull Request fixes issue #1201 

The issue is fixed by updating the score threshold from which the habits get recognised as strong.

### CODE REVIEW

**Comment by phillipthelen** [comment]
This seems to also have some other changes and also a change to the development team. can you take those out please?

**Comment by EricMiddelhove** [comment]
@phillipthelen I believe the additional changes result from branching out of fix-issue-1198 branch instead of development branch. I suggest a rebase of fix-issue-1201 however I am not that experienced with rebasing and do not want to mess anything up.

**Comment by phillipthelen** [comment]
I cherry picked the changes from your PRs and merged them in. Thanks for the work

**Comment by saraolson** [comment]
I've added this contribution to your Habitica profile and granted you a contributor tier 🎊

**Pull request closed without merging**
