### PR TITLE
#1153 - Allow pull down refresh with ScrollView in the Stats view.

### PR DESCRIPTION
**Pull request by tjb**
my Habitica User-ID: e8160fe6-2e6d-494f-b7db-60befa34fe8a

Hello! I am newer to iOS development and want to learn by contributing to open source projects and this one looks amazing. Please any constructive criticism would be appreciated and I hope this is correct! 

I had edits in other files but it seemed Xcode generated (Podlock, User storyboard, Strings, content.xcworkspacedata) but these seemed unneeded...perhaps the User storyboard is needed but it is a lot of changes to the `rect` element that didn't seem necessary for this. Let me know if it does, happy to make another commit!

### CODE REVIEW

**Comment by phillipthelen** [comment]
This looks good, but the User.storyboard file should also have an edit that connects the outlet. Can you check and also add that change to the PR?

**Comment by tjb** [comment]
@phillipthelen updated!

**Comment by tjb** [comment]
@phillipthelen bumping this up. i believe it is good to be merged!

**Comment by saraolson** [comment]
@tjb Thank you again for fixing this up! This PR will also be included in iOS version 3.8. I've added this contribution to your habitica profile and granted you another contributor tier 🎉

**Pull request merged**
