### PR TITLE
Added Version number to About table view

### PR DESCRIPTION
**Pull request by Shadallark**
Added a row to the About screen table view to display the current
version of the App.  I thought it would be useful for users and
developers to know which version of the App they are using.

Please review the method I used to obtain the version number and if it
is acceptable pull this into the master branch.

Shadallark

### CODE REVIEW

**Comment by vIiRuS** [comment]
If you overstretch the main menu to the bottom it actually already contains the version and build number, but this is more obvious.

Can you also add the build number? (as especially beta versions share the same version number but different build numbers )
[[NSBundle mainBundle] objectForInfoDictionaryKey: (NSString *)kCFBundleVersionKey]

**Comment by Shadallark** [comment]
Thanks for the feedback and suggestion @vIiRuS !  I have updated the code to include the build number after the version number on the About form.

**Comment by vIiRuS** [comment]
Everything good! Thanks for the PR!

:+1: 

@crookedneighbor The UUID is 451656cb-6d48-4cd3-9c3b-3e1e2654f975

**Comment by crookedneighbor** [comment]
@Shadallark Tier awarded!

Note that the higher tiers require more work than the lower tiers, so you might not gain tiers quite as quickly.

**Comment by Shadallark** [comment]
Thanks @crookedneighbor .

I am just glad that I can help out a bit.

**Pull request merged**
