### PR TITLE
Fixes #81 Tap Area Size

### LINKED ISSUE #81: Bigger Tap area for checklist indicator
The checklist indicator for dailies and todos should have a tappable area that consists of the entire right part of the cell (currently there is a gap at the top, bottom and to the right

### PR DESCRIPTION
**Pull request by Shadallark**
By adding an invisible button over top of the Checklist Label at the
right end of the cell the Tap Area of the Checklist Label appears
larger.

I am not sure how to subClass the UIButton class to display the label on the button itself without filling the whole button.  If you would like to subClass the UIButton before incorporating these changes I have added notes on which lines can be removed after the button is updated.

### CODE REVIEW

**Comment by vIiRuS** [comment]
The button both has a height constraint and a top/bottom space constraint to the superview. This causes problems when the cell isn't 60 points high, as it can't hold all constraints. Can you remove the constraints for the height?

**Comment by Shadallark** [comment]
Thanks for catching that @vIiRuS.

The height constraints have now been removed.

**Comment by vIiRuS** [comment]
Great. Thanks!

:+1:

**Comment by crookedneighbor** [comment]
@Shadallark notated toward your next tier.

**Pull request merged**
