### PR TITLE
Fix title of Skill screen

### LINKED ISSUE #796: Skill screen uses the title 'Spells' instead of 'Skills'
When you tap 'Use Skills' from the menu, the screen that opens has the title 'Spells'. It should be 'Skills'

### PR DESCRIPTION
**Pull request by HydeHunter2**
Fixes #796

### Changes
- Fix screen title (It was "Spells" instead of "Skills")
Github

----
my Habitica User-ID: af1477b6-509a-4611-b851-d7a8e3a9c02a

### CODE REVIEW

**Comment by HydeHunter2** [comment]
I'd like to implement a switch title between `Spells`/`Skills` like this:
https://github.com/HabitRPG/habitica-ios/blob/b514587ec7713fd9a8a44692255fd4edc1b5db5b/HabitRPG/UI/General/MainMenuViewController.swift#L67-L71
But I have no idea how to pass `habitClass` to .m file

**Comment by Alys** [comment]
As a suggestion from the point of view of wiki documentation and answering questions in the Tavern and Guilds, it would be better if all classes saw the same menu text and screen titles. "Click on Skills" is simpler for new users than "click on Skills if you're a Warrior or Rogue, or Spells if you're a Mage or Healer."

**Comment by saraolson** [comment]
Yes, like @Alys said we want to keep the names consistent across classes so 'Skills' for everyone.

**Comment by HydeHunter2** [comment]
Okay, I got it

**Pull request merged**
