### PR TITLE
Enable alternate app icons on iPad

### PR DESCRIPTION
**Pull request by jaingaurav**
my Habitica User-ID: aec17a4c-e599-4d0b-b021-555e4df7ee11

### CODE REVIEW

**Comment by phillipthelen** [comment]
I thought that alternative app icons only work on iPhones? Do you have documentation about that this works on iPads too?

**Comment by jaingaurav** [comment]
@phillipthelen: I was able to test with the simulator and it seemed to work fine.

**Comment by jaingaurav** [comment]
There's a small footnote here: https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-SW14

> **Important:** If your app contains iPad-specific versions of its icons, the system does not fall back to the alternate icons declared in the platform-agnostic version of CFBundleIcons key. Therefore, if you include any alternate icons in the CFBundleIcons key, you must include them again in your CFBundleIcons~ipad variant.

I was a bit surprised because I didn't think there were iPad-specific icons included. I'm happy to re-generate the icons for the different dimensions if you explain the steps to do so.

**Comment by jaingaurav** [comment]
We can also add protection with `supportsAlternateIcons`. However, I'm not sure what conditions cause this to be false. https://developer.apple.com/documentation/uikit/uiapplication/2806815-supportsalternateicons

**Comment by jaingaurav** [comment]
@phillipthelen: Friendly ping. Are there any further changes you wanted?

**Comment by phillipthelen** [comment]
Sorry for the delay. I was busy with a big Android app update. I was finally able to confirm on my iPad that it does work. Thanks for the work!

**Comment by jaingaurav** [comment]
Thanks a lot! Looking forward to putting up some more fixes.

**Pull request merged**
