### PR TITLE
Add bottom space for the Pets and Mounts related collection views

### PR DESCRIPTION
**Pull request by revolter**
Before | After
--- | ---
Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 41 16 | Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 38 27
Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 41 20 | Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 38 36
Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 41 24 | Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 38 42
Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 41 28 | Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 38 46

my Habitica User-ID: 3712e6e7-6bc1-40f9-87e2-5e3bbdfdc7c1

### CODE REVIEW

**Comment by saraolson** [comment]
@revolter hi there! could you submit a screenshot of how your changes look in the app screens? I'd like to be able to review them visually when the changes relate to the UI/design.

**Comment by revolter** [comment]
I thought about that, as I did in another PR, but I was too tired. <strike>Will do tonight.</strike> Done. Basically, there was no space between the content and the tab bar.

**Comment by revolter** [comment]
I only changed the bottom inset of 4 collection views, the rest of the changes were automatically made by Xcode, probably because I'm the first one who opened that storyboard using Xcode 10.2.

**Comment by saraolson** [comment]
@revolter thank you! looking at the spacing now, could you double it? that way we'll have a nice wide spacer for indicating 'this is definitely the end of the screen'

**Comment by revolter** [comment]
Before | After
--- | ---
Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 41 16 | Simulator Screen Shot - iPhone 8 - 2019-04-17 at 21 23 57
Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 41 20 | Simulator Screen Shot - iPhone 8 - 2019-04-17 at 21 19 41
Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 41 24 | Simulator Screen Shot - iPhone 8 - 2019-04-17 at 21 19 47
Simulator Screen Shot - iPhone 8 - 2019-04-17 at 08 41 28 | Simulator Screen Shot - iPhone 8 - 2019-04-17 at 21 19 50

**Comment by saraolson** [comment]
@revolter looks good on my end! i'm okay with merging the pr whenever you get around to it @phillipthelen

**Comment by phillipthelen** [comment]
Thanks!

I noted this as a contribution in your habitica profile.

**Pull request merged**
