### PR TITLE
Add missing guidelines accept text

### PR DESCRIPTION
**Pull request by revolter**
Before | After
--- | ---
Simulator Screen Shot - iPhone 8 - 2019-04-10 at 20 56 21 | Simulator Screen Shot - iPhone 8 - 2019-04-10 at 21 03 36

my Habitica User-ID: 3712e6e7-6bc1-40f9-87e2-5e3bbdfdc7c1

### CODE REVIEW

**Comment by phillipthelen** [comment]
Hey,

Can you change this to work the same way the other buttons and labels are translated? The text should be in the mainstrings.strings file (there might already be an "Accept" there) and then the buttons text should be set in code through the L10n class that SwiftGen generates. This is needed, so that our translation service can handle all translations properly without me having to constantly export storyboard text.

Thanks!

**Comment by revolter** [comment]
@phillipthelen, Done, but the other text isn't localized.

**Comment by revolter** [comment]
@phillipthelen, This contribution was noted in my habitica profile, right? Asking because I noticed you mentioned this on every PR except this.

**Comment by saraolson** [comment]
@revolter should be on your habitica profile now, ty for pointing it out

**Pull request merged**
