### PR TITLE
Searching tasks' titles and notes.

### LINKED ISSUE #119: make task lists searchable
To make it easier for people with a lot of tasks, there should be search controllers on each task list to search for specific tasks. Shousl search text and notes.

### PR DESCRIPTION
**Pull request by kyle-fox**
Closes #119.

### CODE REVIEW

**Comment by vIiRuS** [comment]
Hi Kyle,

Thank you! But I have two notes to the changes.
Currently when you search for something, you can not dismiss the keyboard without having to undo the search. I would prefer to have the keyboard either be dismissed when the user scrolls the task list or when the "Search" button on the keyboard is pressed. (or ideally both)

The other one is more of an enhancement. The search state is not synced across the different task lists. As the tags are synced to be the same across all lists, I feel like it should also do that with the search.

**Comment by kyle-fox** [comment]
Sorry about the first part - I overlooked it while debugging in the simulator with hardware keyboard. I'll look into sharing the search text throughout the 3 tabs while searching, because that sounds like it'd be a good idea

**Comment by kyle-fox** [comment]
Hi Phillip! The search query is now shared between tabs! I chose to do this through a singleton that allows us to access and manipulate the string from anywhere as opposed to through a property in the parent view controller, so I can use a similar implementation to search rewards, which has a different parent further up the hierarchy. This will also allow extension of the search functionality and further shared searches throughout any future features, if you choose to use it.  

Let me know what you think.

**Comment by kyle-fox** [comment]
See comment about switching tabs when sharing the search query between tabs in https://github.com/HabitRPG/habitrpg-ios/issues/132 - might want to consider this before merging

**Comment by vIiRuS** [comment]
The synced search looks good! No complaints here.
Displaying something when the list is empty is a good idea (probably should be different depending on if you are searching for something or not ). For simplicity/clarity reasons a second PR with the empty state code is probably preferable.
The issue with the non dismissable keyboard is still there right? Once that is resolved i'll merge this in

**Comment by kyle-fox** [comment]
The keyboard dismissing should have been fixed in https://github.com/kyle-fox/habitrpg-ios/commit/c8326c0a6ed01a1f78bae81c06ac5e3c908efe87, just below your first comment here. Let me know if you're still having the isssue!

**Comment by vIiRuS** [comment]
Oh, okay! Sorry for that. Haven't been able to test it on a device yet. Will do that tomorrow.

**Comment by kyle-fox** [comment]
👍

**Comment by vIiRuS** [comment]
Works great! Thanks a lot!

:+1: 

@crookedneighbor 16fa5d4d-6729-4a7d-af3e-26a25850b5b8

**Comment by crookedneighbor** [comment]
Noted toward your next tier.

**Pull request merged**
