### PR TITLE
Fix emoji strike through in checkbox (#1315)

### PR DESCRIPTION
**Pull request by tjb**
my Habitica User-ID: e8160fe6-2e6d-494f-b7db-60befa34fe8a

### CODE REVIEW

**Comment by tjb** [comment]
For those curious this stackoverflow helped me out: https://stackoverflow.com/questions/56470728/swift-nsattributedstring-emojis

**Comment by saraolson** [comment]
Thanks for your help with this! We're currently working on a rather large release that's taking up a lot of our time and energy, but once that's through we'll return back to reviewing and merging PRs. Thanks so much for your patience!

**Comment by tjb** [comment]
no worries at all @saraolson! cheering for the team and the big release :)

**Comment by saraolson** [comment]
@tjb thanks for the positive vibes :) I've gone ahead and added this PR to your Habitica profile as progress towards your next contributor tier :tada:

**Pull request merged**
