### PR TITLE
feat: add avatar view gif support

### PR DESCRIPTION
**Pull request by nivl4**
my Habitica User-ID: 51102111-ed4a-4f13-972b-705a3c1e5808

- change avatar image generation to layers of views generation
- layer image cache provided by default with YYWebImage
- add support for customizable item position eg.`weapon_special_critical`

**NOTE:**
the follow images are currently missing on s3:
https://habitica-assets.s3.amazonaws.com/mobileApp/images/head_special_0.gif
https://habitica-assets.s3.amazonaws.com/mobileApp/images/head_special_1.gif
https://habitica-assets.s3.amazonaws.com/mobileApp/images/shield_special_0.gif
https://habitica-assets.s3.amazonaws.com/mobileApp/images/weapon_special_0.gif
https://habitica-assets.s3.amazonaws.com/mobileApp/images/slim_armor_special_1.gif
https://habitica-assets.s3.amazonaws.com/mobileApp/images/broad_armor_special_1.gif

screenshots:
header
party-members
party-member-detail
level-up

### CODE REVIEW

**Comment by vIiRuS** [comment]
Sorry for the late response.

Not sure if I like this approach. The reason I went with the current/static approach, is that for displaying it only uses a single static image in a single imageview and is this fairly resource friendly. This has up to 23 imageviews with images. All of which are potentially animated (and the number of layers will likely grow, p.e. with the addition of the wheelchairs). Have you tested performance and memory consumption? How much does this change affect that?

**Comment by nivl4** [comment]
@vIiRuS 
I had the same concern about performance and memory usage before I started implementing this, so I did some preliminary tests before. It seems the memory usage is about the same or less than the current static image generation method. Speed wise,  from what I can see, the UIView layers seem to be faster than the drawInRect image method.

I think it would be awesome if the avatar/hero box can have gif support like on the web version, so I implemented it.

here's a simple comparison: 

current master [commit c820a6c2616f03ba5a162d5edfa8213fd18ee5fc] without gif support:
c820a6c2616f03ba5a162d5edfa8213fd18ee5fc


with gif support:
91157f5d68cfebb6ca9c42efbc5984a7d662ce22

**Comment by nivl4** [comment]
@vIiRuS I just added [HRPGSharingManager takeSnapshotOfView](https://github.com/nivl4/habitrpg-ios/blob/feat/avatar-gif-support/HabitRPG/TableViewController/HRPGSharingManager.m#L18) utility method to convert avatar view to static image for social sharing purpose.

**Comment by vIiRuS** [comment]
Awesome, thanks!

I am currently in the middle of a big refactoring for the upcoming APIv3 launch, so I'm holding off on merging this until then. Just so you're not wondering.

**Pull request merged**
