### PR TITLE
Created an iPad version of the app

### PR DESCRIPTION
**Pull request by Shadallark**
I have created an iPad version of the app by copying everything from the iPhone storyboard to the iPad storyboard.  This makes the app look a whole lot better on the iPad than it does when using the iPhone version.

Shadallark

### CODE REVIEW

**Comment by Shadallark** [comment]
Oops, should have said that this would deal with the recently created issue #140.

Shadallark

**Comment by Shadallark** [comment]
I am going to look into using one Storyboard for both the iPhone and iPad.  I will let you know the results of my testing.  Until then, this pull request is on hold.

**Comment by Shadallark** [comment]
Until I figure out how to get the button overlay screens (Equip / Unequip / Sell / Feed / etc.) to work correctly on the iPad version (using the iPhone storyboard) this pull request should remain on hold (or be closed).

**Comment by Shadallark** [comment]
Ok.  This Pull Request is ready to go.  To summarize, this Pull Request:
* removes the Main_iPad.storyboard file;
* renames the Main_iPhone.storyboard to Main.storyboard;
* updates the locations that use UIActionSheet to call it using a method acceptable to the iPhone and the iPad;
* sets the Use Size Classes feature (Note: this feature is not supported by XCode 5 or earlier).

Things that now work on iPhone (simulator) and iPad (Mini 2 physical device) include:
* casting spells;
* adding Habits, Dailies, To-Dos, and checklists;
* writing messages in the tavern and to my party;
* viewing party members;
* viewing news;
* settings;
* the About screen;
* changing my shirt/hair/skin/etc.;
* hatching or selling eggs;
* starting quests;
* feeding, equipping, and unequipping pets;
* equipping and unequipping mounts;
* searching; and 
* purchase rewards.

If there is anything else that anyone would like me to look into before this pull request can be merged let me know.

**Comment by vIiRuS** [comment]
Good so far, but I'm still having a few issues (especially on iOS 9, but I'm not sure if that is our fault or a beta bug)

Rewards and Spells are not scaled big enough for the text. The labels "spill over".
screen shot 2015-08-03 at 11 56 33

This issue also concerns all tableviews, as they have a property `screenWidth`, which is always the width of the screen (but when it's rotated it has to be set to the height and the tableview has to reload all data)
this can be solved by adding a `  [[NSNotificationCenter defaultCenter] addObserver:self  selector:@selector(orientationChanged:)    name:UIDeviceOrientationDidChangeNotification  object:nil];
`notification observer to the `HRPGBaseTableViewController` class, that calls a method that sets the width (depending on current rotation) and then calls `[self.tableView reloadData]`.

The Topheader isn't scaled when the device is rotated. This is actually a bit more trickier. Unfortunately there is no way to redo the layout without redoing the whole view. Ideally this should be redone with autolayout, but that would be a bit off-topic for this PR. For now you can throw away the topheader and simply create a new one. I'll redo this with autolayout soon.

I'm also having a drawing error with the progress bars and the level indicator in the topheader. Their border isn't drawn correctly.
img_0001

That screen also shows the issue with iOS 9. The detail indicators and divider insets somehow are very strange. I'm not sure why though.

But this already is a lot better than the upscaled iPhone version :tada:

**Comment by wrongtarget** [comment]
Yes! This is awesome news and great progress. I hope this can be deployed some time soon, hating the Habitica experience on my iPad so far :(

**Comment by Shadallark** [comment]
@vIiRuS is there a reason that the self.screenWidth needs to be set in viewDidLoad?  In the code I am uploading in a few minutes I am setting it by posting a notification of UIDeviceOrientationDidChangeNotification in viewWillAppear right after setting the AddObserver notification observer.  If I do it this way it checks if the user is starting the App in Portrait or Landscape modes.

If it is okay with you I recommend creating new issues for the Top Header not being scaled correctly, and the border not drawing correctly and separate them from this Pull Request.  Neither of those issues affects functionality.  If you would prefer to keep them included in this Pull Request that is fine, I can work on them later.

**Comment by vIiRuS** [comment]
it was set there because the value should be available as soon as possible (not entirely sure when cell heights are calculated).
I'm not sure if posting the notification without actually changing the orientation can cause problems. Is there an argument against calling the orientationChanged method directly and passing it nil as a notification? Calling it directly prevents issues that may arise from calling methods used for responding to interface rotation when there was none.

I'll do final tests tomorrow and then probably merge this in.

**Comment by Shadallark** [comment]
Sorry @vIiRuS not quite ready to go.  Some new bugs I need to confirm and deal with first:
* cannot feed pets (option shows up but clicking on it does nothing)
* trying to view party members sends the app screen away; bringing it back from the list of open apps shows it has jumped back to the To-Dos screen
* equipped items do not show up as equipped if they are the only item for that body part even though they are equipped (see images)

image
image

**Comment by Shadallark** [comment]
I figured out the feeding issue.  Because the iPad converts an UIActionSheet into a popover we need to use `actionSheet:didDismissWithButtonIndex` rather than `actionSheet:clickedButtonAtIndex` as the popover has to be dismissed prior to another modal view being opened.

Testing this on the iPad (device) and on the iPhone (simulator) shows this method will work correctly and allow users to feed their pets.

**Comment by Shadallark** [comment]
Wow, I was completely stumped on how to fix the issue that was occurring when I tried to view party members, but managed to figure it out as I was drafting a long winded post here to ask for help!

I had to move the call to `[super viewDidLoad]` until further down in the `viewDidLoad` function so that enough information was available for the `[self.tableView reloadData]` command in the `HRPGBaseViewController` to function correctly.

**Comment by Shadallark** [comment]
The equipment issue noted above where some of my gear was not showing up as Equipped in the details screen was not an issue with this change over to the iPad version; the `isEquippedBy` checks of the different equipment were missing for `Body` and `Eyewear`.  Adding in those checks fixes the issue.

Therefore, @vIiRuS this Pull Request is ready for your final testing and merge.  Let me know if you run into any other issues.

**Comment by vIiRuS** [comment]
Looks good! I'll merge this in now. The header and the incorrectly sized cells still have to be fixed before the next release, but I'll create seperate Issues for that.

:+1:

**Comment by crookedneighbor** [comment]
@Shadallark notated toward your next tier.

**Comment by crookedneighbor** [comment]
Since this was a bigger feature, I've awarded you a tier for it.

**Comment by vIiRuS** [comment]
As an update for completeness: I already fixed the header sizing and am currently looking into the wrong cell sizes

**Comment by Shadallark** [comment]
Thanks @crookedneighbor !  For your records @kyle-fox and @vIiRuS provided plenty of great advice and feedback on this pull request / feedback as well.

**Pull request merged**
