### PR TITLE
Xcode: add shared scheme for HabiticaTests

### PR DESCRIPTION
**Pull request by jmoody**
### Motivation

I wanted to run the unit tests, but there was no scheme for the HabiticaTests.

I am assuming that the maintainers have an un-shared HabiticaTests scheme.  The alternative to this PR is for a maintainer with an existing HabiticaTests scheme to touch the "Shared" button and commit the change.

### CODE REVIEW

**Comment by jmoody** [comment]
Ah!  I learned something new!  You don't need an explicit scheme for running the XCTests - just use Command + U.  I wonder when that changed. ;)

I think this PR still has merit because I believe that `xcodebuild` might need an explicit scheme on the command line.  This will be essential if you want to wire this repo up to a Travis or Jenkins.  I am testing this assertion now, but I can't get past this error on the command line.

```
Pods/FontAwesomeIconFactory/FontAwesomeIconFactory/iOS/NIKFontAwesomeImageView.m:166:21: error: unknown type name 'NSColor'
```

Feel free to merge or close this PR.

**Comment by vIiRuS** [comment]
Hi,

Yes, I was using the basic cmd+U method to run tests so far. But if the extra scheme offers additional/better configuration options we can also merge it in

**Comment by jmoody** [comment]
> Can you build and run the app or does that also give an error?

I can build and run from Xcode - the tests and the app.

> The error is strange. 

I am almost 100% certain that CocoaPods is to blame.  I have had problems running `xcodebuild` from the command line in CocoaPods repos.

If you haven't guessed already, I am a dev-ops professional. :)

**Comment by jmoody** [comment]
If you don't plan on integrating with CI (Travis and/or Jenkins), I believe you can close this PR.

**Comment by vIiRuS** [comment]
Do you know if there is a way to fix the problem if it's related to cocoapods?
Dev-Ops professional sounds great! :D

I would definitely like to add CI at some point. I haven't pursued it yet, as the amount of tests is still very… little. So having it capable of running there would be great.

**Comment by jmoody** [comment]
I was wrong.  It is not a problem with CocoaPods _per se_, but a problem with the XCTests of one of the libraries:

Two references to NSColor in an iOS file:

* https://github.com/nschum/FontAwesomeIconFactory/blob/master/FontAwesomeIconFactory/iOS/NIKFontAwesomeImageView.m#L166
* https://github.com/nschum/FontAwesomeIconFactory/blob/master/FontAwesomeIconFactory/iOS/NIKFontAwesomeImageView.m#L170

I am afraid we are getting a little off topic in this issue.  Now that I know you are interested in CI, I will make a PR that can run the tests from the command line.

**Comment by jmoody** [comment]
@vIiRuS https://github.com/nschum/FontAwesomeIconFactory/pull/12

**Pull request closed without merging**
