### PR TITLE
Change due date display style on tasks, issue #1069

### PR DESCRIPTION
**Pull request by rolisanchez**
This is the work related to issue #1069.

The display of words such as "today", "tomorrow" and "in X days" is done through localization.

I created 2 different DateFormatters in TodoTableViewDataSource for displaying the 2 different styles: 1) localized short without year, and 2) with year, using preferred language to display correct month order.

Besides removing the "due" from the text, I also removed it from German (fällig), Spanish (Vence), French (Échéance), Portuguese (Devido/Prazo), Italian (Scade) 

I thought about removing the 到期 in Chinese and 期限 in Japanese, but this might need some discussion. Also I tried using the app in Traditional Chinese, which I’m familiar with, but this does not have a localization. Would it make sense to default to Simplified Chinese since Traditional is not available? (might need to create another issue - default to Simplified Chinese when Traditional not available)

I'm not familiar with Hebrew, Romanian, Russian, Dutch, Polish, Bulgarian, Czech, Croatian grammar so didn’t make any changes to remove the "Due" equivalent.

---

my Habitica User-ID: ccf1ce82-1e91-4dd1-9b17-aa4fc4c4f2f2

### CODE REVIEW

**Comment by rolisanchez** [comment]
Screenshots in English, Spanish and Portuguese. 

2 cases: 1) Today+Before (yesterday and last year), and 2) Tomorrow+Later (tomorrow, in 3 days, next month, next year)

Today and Before - EN
Today and Before - ES
Today and Before - PT
Tomorrow and Later - EN
Tomorrow and Later - ES
Tomorrow and Later - PT

**Comment by saraolson** [comment]
@rolisanchez for your question on the trad/simplified chinese, it's best to make a separate issue for that but I do agree with making simplified the default. we rely on contributors for out translation work, so I can't speak to various other languages but leaving them as is for now is okay.

**Comment by rolisanchez** [comment]
Solved merge conflicts with the fix for Issue #1097

**Comment by saraolson** [comment]
@rolisanchez I've also added this contribution to your habitica profile 🎊

**Pull request merged**
